
#### 
# Overridden configurations
# Set by environment variable "BLUEPRINT_CONFIG", or by the 'default_config' key, or in code
####   

hackathon :
  llm:
    models:
      default: gpt_oss120_openrouter
  embeddings:
    models:
      default: qwen3_06b_deepinfra
  vector_store:
    default : Chroma
  cli:
    commands:  
    - genai_tk.main.commands_core:register_commands
    - genai_tk.main.commands_agents:register_commands
    - genai_tk.main.commands_extra:register_commands
    - genai_blueprint.hackathon.cli_commands.commands_baml:register_baml_commands

  paths:
    team_sp: ${oc.env:ONEDRIVE, undefined_path}/Team Hackathon DATA&AI - Team Data AI Kackathon
    hackathon_sp: ${oc.env:ONEDRIVE, undefined_path}/Hackathon Legal & Compliance - Général

  # TODO : Allow 'default' and tagged kv_store
  kv_store: 
    file: 
      path: ${hackathon.paths.team_sp}/kv_store
