
#### 
# Overridden configurations
# Set by environment variable "BLUEPRINT_CONFIG", or by the 'default_config' key, or in code
####   

hackathon :
  llm:
    models:
      default: gpt_oss120_openrouter
  embeddings:
    models:
      default: qwen3_06b_deepinfra
  vector_store:
    default : Chroma
  cli:
    commands:  
    - genai_tk.main.commands_core:register_commands
    - genai_tk.main.commands_agents:register_commands
    - genai_tk.main.commands_extra:register_commands
    - genai_blueprint.hackathon.cli_commands.commands_baml:register_baml_commands

  kv_store: 
    file: 
      path: ${paths.data_root}/kv_store
    sql: 
      path: ${paths.postgres}
