langchain_agents:

  - name: "filesystem"
    pre_prompt: You have the ability to manipulate file system.  Is the user ask somethin else, refuse politly.
    tools:  
      - factory: genai_tk.tools.langchain.search_tools_factory:create_search_function
        verbose: true
    mcp_servers:
      - "filesystem"
    examples:
      - "What are the configuration files in current directory"

  - name: "Web Research"
    mcp_servers:
      - "playwright"
    examples:
      - "Research the latest AI developments on OpenAI's website"
      - "Find information about quantum computing on IBM's website"
      - "Connect to atos.net with a browser, find the page with blogs, and get list of recent blog articles"
  
  # - name: "filesystem"
  #   #re_prompt: You have the ability to manipulate file system 
  #   tools:  
  #     - factory: genai_tk.tools.langchain.search_tools_factory:create_search_function
  #       verbose: true
  #   mcp_servers:
  #     - "filesystem"
  #   examples:
  #     - "What are the configuration files in current directory"

  - name: "legal"
    tools: 
      # - function: hackathon.test_baml:analyse_legal_contract 

      - class: langchain_tavily:TavilySearch 
        max_results : 5
        include_domains:  
        - https://www.data.gouv.fr/datasets/legi-codes-lois-et-reglements-consolides
        - https://www.journal-officiel.gouv.fr'
    examples:
      - "changements de réglementation sur la regulation des marchés financiers."


